platform: "tensorrt_plan"
max_batch_size: 1
default_model_filename: "efficientnet_110_with_softmax.onnx_b1_fp16.engine"

input [
  {
    name: "input"    # 必须与ONNX输入名称一致
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 224, 224 ]
    is_shape_tensor: false
  }
]

output [
  {
    name: "probabilities"  # 与导出时的output_names一致
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]

dynamic_batching {
  preferred_batch_size: [ 1 ]
  max_queue_delay_microseconds: 0  # 最大批处理等待时间（微秒）
}

instance_group [
  {
    count: 1           # GPU实例数
    kind: KIND_GPU     # 使用GPU加速
    gpus: [ 0 ]     # 使用的GPU设备ID
  }
]