name: "Secondary_VehicleTypes"
platform: "tensorrt_plan"
max_batch_size: 16
default_model_filename: "resnet18_vehicletypenet_pruned.onnx_b16_gpu0_int8.engine"
input [
  {
    name: "input_1:0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, 224, 224]
  }
]
output [
  {
    name: "predictions/Softmax:0"
    data_type: TYPE_FP32
    dims: [6]
  }
]
instance_group [
  {
    kind: KIND_GPU
    count: 1
    gpus: 0
  }
]
